import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { GetStaticProps } from 'next';
import db from '../lib/sqlite/db';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>...</div>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  await db.sync();
  console.log(`All models were synchronized successfully.`);

  return {
    props: {
      createdDb: true,
    },
  };
};
